import Route from 'ember-route';

export default Route.extend({
  model() {
    return {
      general: [
        {icon: "check"},
        {icon: "check-curve"},
        {icon: "check-simple"},
        {icon: "simple-remove"},
        {icon: "arrows-tail-right"},
        {icon: "triangle-down"},
        {icon: "arrows-small-right"},
        {icon: "arrows-small-left"},
        {icon: "arrows-small-top"},
        {icon: "arrows-small-down"},
        {icon: "arrows-stre-right"},
        {icon: "arrows-stre-left"},
        {icon: "arrows-stre-top"},
        {icon: "arrows-stre-down"},
        {icon: "pinch"},
        {icon: "stretch"},
        {icon: "dots"},
        {icon: "menu"},
        {icon: "alert-i"},
        {icon: "alert-?"},
        {icon: "round-e-info"},
        {icon: "alert-circle-?"},
        {icon: "square-e-alert"},
        {icon: "refresh"},
        {icon: "search"},
        {icon: "text"},
        {icon: "count"},
        {icon: "int"},
        {icon: "float"},
        {icon: "calendar"},
        {icon: "time"},
        {icon: "email"},
        {icon: "telephone"},
        {icon: "moblie"},
        {icon: "pin"},
        {icon: "building"},
        {icon: "business"},
        {icon: "language"},
        {icon: "users"},
        {icon: "lock"},
        {icon: "credit-card"},
        {icon: "share"},
        {icon: "link"},
        {icon: "next"},
        {icon: "upload"},
        {icon: "download"},
        {icon: "camera"},
        {icon: "video"},
        {icon: "microphone"},
        {icon: "scan"},
        {icon: "barcode"},
        {icon: "bardcode-qr"},
        {icon: "cart"},
        {icon: "gift"},
        {icon: "shapes"},
        {icon: "bell"},
        {icon: "trash"},
        {icon: "ranking"},
      ],
      basic: [
        {icon: "checkbox"},
        {icon: "checkbox-active"},
        {icon: "radio"},
        {icon: "radio-active"},
      ],
      rating: [
        {icon: "love-favorite"},
        {icon: "love-favorite-active"},
        {icon: "star"},
        {icon: "star-active"},
        {icon: "thumbs-up"},
        {icon: "thumbs-up-active"},
        {icon: "baloon"},
        {icon: "baloon-active"},
        {icon: "crown"},
        {icon: "crown-active"},
      ],
      location: [
        {icon: "location"},
        {icon: "positioning"},
        {icon: "location-successful"},
        {icon: "location-failed"},
        {icon: "map-location"},
        {icon: "present-gift"},
        {icon: "sms"},
        {icon: "password"},
        {icon: "captcha"},
      ],
      large: [
        {icon: "upload-image"},
      ]
    };
  }
});
